# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.3.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.3.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/SeanSmith/Junior/cs585/a4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/SeanSmith/Junior/cs585/a4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.3.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.3.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/SeanSmith/Junior/cs585/a4/CMakeFiles /Users/SeanSmith/Junior/cs585/a4/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/SeanSmith/Junior/cs585/a4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Batman_ABGreedy

# Build rule for target.
Batman_ABGreedy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Batman_ABGreedy
.PHONY : Batman_ABGreedy

# fast build rule for target.
Batman_ABGreedy/fast:
	$(MAKE) -f CMakeFiles/Batman_ABGreedy.dir/build.make CMakeFiles/Batman_ABGreedy.dir/build
.PHONY : Batman_ABGreedy/fast

#=============================================================================
# Target rules for targets named Batman_KF

# Build rule for target.
Batman_KF: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Batman_KF
.PHONY : Batman_KF

# fast build rule for target.
Batman_KF/fast:
	$(MAKE) -f CMakeFiles/Batman_KF.dir/build.make CMakeFiles/Batman_KF.dir/build
.PHONY : Batman_KF/fast

Batman_ABGreedy.o: Batman_ABGreedy.cpp.o

.PHONY : Batman_ABGreedy.o

# target to build an object file
Batman_ABGreedy.cpp.o:
	$(MAKE) -f CMakeFiles/Batman_ABGreedy.dir/build.make CMakeFiles/Batman_ABGreedy.dir/Batman_ABGreedy.cpp.o
.PHONY : Batman_ABGreedy.cpp.o

Batman_ABGreedy.i: Batman_ABGreedy.cpp.i

.PHONY : Batman_ABGreedy.i

# target to preprocess a source file
Batman_ABGreedy.cpp.i:
	$(MAKE) -f CMakeFiles/Batman_ABGreedy.dir/build.make CMakeFiles/Batman_ABGreedy.dir/Batman_ABGreedy.cpp.i
.PHONY : Batman_ABGreedy.cpp.i

Batman_ABGreedy.s: Batman_ABGreedy.cpp.s

.PHONY : Batman_ABGreedy.s

# target to generate assembly for a file
Batman_ABGreedy.cpp.s:
	$(MAKE) -f CMakeFiles/Batman_ABGreedy.dir/build.make CMakeFiles/Batman_ABGreedy.dir/Batman_ABGreedy.cpp.s
.PHONY : Batman_ABGreedy.cpp.s

Batman_KF.o: Batman_KF.cpp.o

.PHONY : Batman_KF.o

# target to build an object file
Batman_KF.cpp.o:
	$(MAKE) -f CMakeFiles/Batman_KF.dir/build.make CMakeFiles/Batman_KF.dir/Batman_KF.cpp.o
.PHONY : Batman_KF.cpp.o

Batman_KF.i: Batman_KF.cpp.i

.PHONY : Batman_KF.i

# target to preprocess a source file
Batman_KF.cpp.i:
	$(MAKE) -f CMakeFiles/Batman_KF.dir/build.make CMakeFiles/Batman_KF.dir/Batman_KF.cpp.i
.PHONY : Batman_KF.cpp.i

Batman_KF.s: Batman_KF.cpp.s

.PHONY : Batman_KF.s

# target to generate assembly for a file
Batman_KF.cpp.s:
	$(MAKE) -f CMakeFiles/Batman_KF.dir/build.make CMakeFiles/Batman_KF.dir/Batman_KF.cpp.s
.PHONY : Batman_KF.cpp.s

Hungarian.o: Hungarian.cpp.o

.PHONY : Hungarian.o

# target to build an object file
Hungarian.cpp.o:
	$(MAKE) -f CMakeFiles/Batman_KF.dir/build.make CMakeFiles/Batman_KF.dir/Hungarian.cpp.o
.PHONY : Hungarian.cpp.o

Hungarian.i: Hungarian.cpp.i

.PHONY : Hungarian.i

# target to preprocess a source file
Hungarian.cpp.i:
	$(MAKE) -f CMakeFiles/Batman_KF.dir/build.make CMakeFiles/Batman_KF.dir/Hungarian.cpp.i
.PHONY : Hungarian.cpp.i

Hungarian.s: Hungarian.cpp.s

.PHONY : Hungarian.s

# target to generate assembly for a file
Hungarian.cpp.s:
	$(MAKE) -f CMakeFiles/Batman_KF.dir/build.make CMakeFiles/Batman_KF.dir/Hungarian.cpp.s
.PHONY : Hungarian.cpp.s

Kalman.o: Kalman.cpp.o

.PHONY : Kalman.o

# target to build an object file
Kalman.cpp.o:
	$(MAKE) -f CMakeFiles/Batman_KF.dir/build.make CMakeFiles/Batman_KF.dir/Kalman.cpp.o
.PHONY : Kalman.cpp.o

Kalman.i: Kalman.cpp.i

.PHONY : Kalman.i

# target to preprocess a source file
Kalman.cpp.i:
	$(MAKE) -f CMakeFiles/Batman_KF.dir/build.make CMakeFiles/Batman_KF.dir/Kalman.cpp.i
.PHONY : Kalman.cpp.i

Kalman.s: Kalman.cpp.s

.PHONY : Kalman.s

# target to generate assembly for a file
Kalman.cpp.s:
	$(MAKE) -f CMakeFiles/Batman_KF.dir/build.make CMakeFiles/Batman_KF.dir/Kalman.cpp.s
.PHONY : Kalman.cpp.s

Tracker.o: Tracker.cpp.o

.PHONY : Tracker.o

# target to build an object file
Tracker.cpp.o:
	$(MAKE) -f CMakeFiles/Batman_KF.dir/build.make CMakeFiles/Batman_KF.dir/Tracker.cpp.o
.PHONY : Tracker.cpp.o

Tracker.i: Tracker.cpp.i

.PHONY : Tracker.i

# target to preprocess a source file
Tracker.cpp.i:
	$(MAKE) -f CMakeFiles/Batman_KF.dir/build.make CMakeFiles/Batman_KF.dir/Tracker.cpp.i
.PHONY : Tracker.cpp.i

Tracker.s: Tracker.cpp.s

.PHONY : Tracker.s

# target to generate assembly for a file
Tracker.cpp.s:
	$(MAKE) -f CMakeFiles/Batman_KF.dir/build.make CMakeFiles/Batman_KF.dir/Tracker.cpp.s
.PHONY : Tracker.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Batman_ABGreedy"
	@echo "... Batman_KF"
	@echo "... Batman_ABGreedy.o"
	@echo "... Batman_ABGreedy.i"
	@echo "... Batman_ABGreedy.s"
	@echo "... Batman_KF.o"
	@echo "... Batman_KF.i"
	@echo "... Batman_KF.s"
	@echo "... Hungarian.o"
	@echo "... Hungarian.i"
	@echo "... Hungarian.s"
	@echo "... Kalman.o"
	@echo "... Kalman.i"
	@echo "... Kalman.s"
	@echo "... Tracker.o"
	@echo "... Tracker.i"
	@echo "... Tracker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

